# Generated by Django 4.1.5 on 2023-01-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="tags",
            new_name="tag",
        ),
    ]
